revised

diff --git a/MHS35-show b/MHS35-show
--- a/MHS35-show
+++ b/MHS35-show
@@ -2,62 +2,69 @@
 
 sudo ./system_backup.sh
 
-if [ -f /etc/X11/xorg.conf.d/40-libinput.conf ]; then
-sudo rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
-fi
-if [ ! -d /etc/X11/xorg.conf.d ]; then
-sudo mkdir -p /etc/X11/xorg.conf.d
-fi
 sudo cp ./usr/mhs35-overlay.dtb /boot/overlays/
 sudo cp ./usr/mhs35-overlay.dtb /boot/overlays/mhs35.dtbo
 
-root_dev=`grep -oPr "root=[^\s]*" /boot/cmdline.txt | awk -F= '{printf $NF}'`
-if test "$root_dev" = "/dev/mmcblk0p7";then
-sudo cp -rf ./boot/config-noobs-nomal.txt ./boot/config.txt.bak
-else
-sudo cp -rf ./boot/config-nomal.txt ./boot/config.txt.bak
-sudo echo "hdmi_force_hotplug=1" >> ./boot/config.txt.bak
-fi
-sudo echo "dtparam=i2c_arm=on" >> ./boot/config.txt.bak
-sudo echo "dtparam=spi=on" >> ./boot/config.txt.bak
-sudo echo "enable_uart=1" >> ./boot/config.txt.bak
-sudo echo "dtoverlay=mhs35:rotate=90" >> ./boot/config.txt.bak
-sudo echo "hdmi_group=2" >> ./boot/config.txt.bak
-sudo echo "hdmi_mode=1" >> ./boot/config.txt.bak
-sudo echo "hdmi_mode=87" >> ./boot/config.txt.bak
-sudo echo "hdmi_cvt 480 320 60 6 0 0 0" >> ./boot/config.txt.bak
-sudo echo "hdmi_drive=2" >> ./boot/config.txt.bak
-sudo cp -rf ./boot/config.txt.bak /boot/config.txt
 
+# Inject cmdline.txt
+if [ ! -s /boot/cmdline.txt ]; then
+    echo "Error: /boot/cmdline.txt not found, please mount your /boot folder!"
+    exit 1
+fi
+for opt in "fbcon=map:10" "fbcon=font:ProFont6x11" "logo.nologo"; do
+	if [ `grep "$opt" /boot/cmdline.txt | wc -c` != 0 ]; then
+		continue
+	fi
+	echo -n " $opt" >>/boot/cmdline.txt
+done
+
+
+# Inject config.txt
+if [ ! -s /boot/config.txt ]; then
+    echo "Error: /boot/config.txt not found, please mount your /boot folder!"
+    exit 1
+fi
+for config in "dtparam=i2c_arm=on" "dtparam=spi=on" "enable_uart=1" "dtoverlay=mhs35:rotate=90" \
+	"hdmi_group=2" "hdmi_mode=82" "hdmi_drive=2"; do
+	if [ `grep "^$config" /boot/config.txt | wc -l` != 0 ]; then
+		continue
+	fi
+	if [ `grep "^#\+$config" /boot/config.txt | wc -l` != 0 ]; then
+		sudo sed -i "s/^#\+$config/$config/g" /boot/config.txt
+	fi
+done
+
+
+sudo rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
+sudo mkdir -p /etc/X11/xorg.conf.d
 sudo cp -rf ./usr/99-calibration.conf-mhs35-90  /etc/X11/xorg.conf.d/99-calibration.conf
 sudo cp -rf ./usr/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
-if test "$root_dev" = "/dev/mmcblk0p7";then
-sudo cp ./usr/cmdline.txt-noobs /boot/cmdline.txt
-else
-sudo cp ./usr/cmdline.txt /boot/
-fi
+
 sudo cp ./usr/inittab /etc/
-#sudo cp ./boot/config-mhs35.txt /boot/config.txt
 sudo touch ./.have_installed
 echo "gpio:resistance:mhs35:90:480:320" > ./.have_installed
 
 #FBCP install
 wget --spider -q -o /dev/null --tries=1 -T 10 https://github.com
 if [ $? -eq 0 ]; then
-sudo cp -rf ./usr/99-fbturbo-fbcp.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
-sudo cp -rf ./etc/rc.local /etc/rc.local
-sudo apt-get install git cmake -y 2> error_output.txt
-result=`cat ./error_output.txt`
-echo -e "\033[31m$result\033[0m"
-grep -q "^E:" ./error_output.txt && exit
-sudo rm -rf rpi-fbcp
-sudo git clone https://github.com/tasanakorn/rpi-fbcp
-sudo mkdir ./rpi-fbcp/build
-cd ./rpi-fbcp/build/
-sudo cmake ..
-sudo make
-sudo install fbcp /usr/local/bin/fbcp
-cd - > /dev/null
+	sudo cp -rf ./usr/99-fbturbo-fbcp.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf
+	sudo apt-get install git cmake -y 2> error_output.txt
+	result=`cat ./error_output.txt`
+	echo -e "\033[31m$result\033[0m"
+	grep -q "^E:" ./error_output.txt && exit
+	sudo rm -rf rpi-fbcp
+	sudo git clone https://github.com/tasanakorn/rpi-fbcp
+	sudo mkdir ./rpi-fbcp/build
+	cd ./rpi-fbcp/build/
+	sudo cmake ..
+	sudo make
+	sudo install fbcp /usr/local/bin/fbcp
+	if [ ! "`grep fbcp /etc/rc.local`" ]; then
+		sed -i "/^exit 0/d" /etc/rc.local
+		echo 'sleep 7 && fbcp &' >>/etc/rc.local
+		echo 'exit 0' >>/etc/rc.local
+	fi
+	cd - > /dev/null
 fi
 #evdev install
 #nodeplatform=`uname -n`
@@ -69,15 +76,14 @@ version=${version##* }
 #version=${version#*#}
 echo $version
 if test $version -lt 2017;then
-echo "reboot"
+	echo "reboot"
 else
-echo "need to update touch configuration"
-sudo dpkg -i -B ./xserver-xorg-input-evdev_1%3a2.10.6-1+b1_armhf.deb 2> error_output.txt
-#sudo apt-get install xserver-xorg-input-evdev  2> error_output.txt
-result=`cat ./error_output.txt`
-echo -e "\033[31m$result\033[0m"
-grep -q "error:" ./error_output.txt && exit
-sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
+	echo "need to update touch configuration"
+	sudo apt-get install xserver-xorg-input-evdev  2> error_output.txt
+	result=`cat ./error_output.txt`
+	echo -e "\033[31m$result\033[0m"
+	grep -q "error:" ./error_output.txt && exit
+	sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
 #echo "reboot"
 fi
 #else
